### PR TITLE
adding MQTTS, misc changes to examples

### PR DESCRIPTION
**Pull request by bwjohns4**
I gave it a try to add SSL to the MQTT and added an example .ino. I can test it out to tomorrow. Also, take a look at two small changes proposed to the https and mqtt examples and let me know if you agree with those changes.

### CODE REVIEW

**Comment by bwjohns4** [comment]
So far, I can't get the MQTT SSL connection to open, I'm stuck at:

```
06:37:04.740 > bgxx: >> AT+QMTOPEN=0,"[private HiveMQ SSL MQTT Broker]",8883
06:37:04.825 > bgxx: << OK
06:37:05.157 > bgxx: << +QMTOPEN: 0,-1
```

I'm still working on it, the -1 error means "Failed to Open Network" per the manual. But I don't know any way to get next level debugging on that. Something like wireshark would certainly be nice.

Any ideas? I do notice that the command to declare the .pem certificate does not actually upload any root certificates, but that doesn't seem to be a problem on the HTTPS implementation.

I changed the SSL version and cipher suites to "allow all" and also tried changing the seclevel.

**Comment by bwjohns4** [comment]
Pretty miserable time trying to connect to HiveMQ. I found a handful of forum posts where others were having the same difficult connecting to the HiveMQ 8883 SSL port. I did get this working with the mosquito test server (test.mosquitto.org:8883), but anything requiring credentials over SSL failed. I got past the previous error where the SSL couldn't connect and was stuck after doing the QMTCONN and sending credentials with the error "Connection Refused: Not Authorized" ie "+QMTCONN: 0,0,5.

I left the seclevel at 0 to not verify the server certificate since no CA certs are able to uploaded at this point.

Trying to get the HiveMQ 8883 with credentials to work I tried:

1. adjusting the seclevel between 0 -> 1,
2. changing the coding from IRI -> GSM -> USC2
3. Changing the mode from Text to PDU, then back
4. Tried various different Client ID's to avoid unusual characters, etc.
5. I'm sure the user/pass was correct because I'm already connecting to that same HiveMQ server via Arduino WiFi using WiFiClientSecure() and doing .setInsecure() which also doesn't verify the server cert. And the Arduino WiFi connection works fine.
6. My RSSI is around -80 to -82, sometimes -85 ish. Not sure if that's a contributor. I wouldn't think so since mosquitto works fine.

Here's a few forum posts where others have also had this issue:
https://forums.quectel.com/t/bg95-connection-issues/13969
https://community.hivemq.com/t/client-is-not-authorized-to-connect/856
https://community.hivemq.com/t/hivemq-cloud-server-rejects-connection-to-lte-device/600/5

**Review by zimbora — APPROVED** [review]
demo-mqtt topic_len is the size of topic array. I have added a method for that.

demo-mqtts should use same method also.

I think I lost the configurations that you have changed for ssl, I will check it better after this merge

**Review by zimbora — APPROVED** [review]

**Comment by zimbora** [comment]
Send me the credentials for a mqtt broker with ssl connection. I can test it on my side, just to confirm that I have the same result of you.

Furthermore you can see the following example on modem datasheet. It seems that you need to upload your certificate.
In https case (tcp+ssl) there is already one certificate present in the module that can validate the majority of the domains

Screenshot 2022-11-28 at 11 58 08

Screenshot 2022-11-28 at 11 58 33

**Comment by bwjohns4** [comment]
Here are the credentials:

URL: 54cec30ac1ea4134a76f05c7275bd055.s2.eu.hivemq.cloud
username: keepconnectQ
password: Qtestpassword

Is it actually needed to upload a certificate? Doing SSL MQTT to the mosquitto server works fine with the seclevel set to not validate certs.

**Comment by zimbora** [comment]
Probably this is a private server and the certificate was not validated in some public entity as letsencrypt. I can't even connect to it with mqtt explorer client. I didn't read too much about it and so, at this moment it will be hard for me help you more. Maybe in a few weeks I can add some extra help.
However, send me also the mosquitto server credentials please, to also test it

**Comment by bwjohns4** [comment]
The mosquitto server is just test.mosquitto.org:8883 with no credentials. 

That's odd about the Hive server. I'm able to connect to it without issue when using ESP32 WifiClientSecure on a normal WiFi MQTT session. I have a case open with Quectel as well, I'll let you know what they say.

**Pull request merged**
